import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';

export default [
  {
    ignores: [
      'node_modules',
      'dist',
      'build',
      '**/*.min.js',
      '**/*.min.css',
      'coverage',
      '.next',
      '.vite',
      '.turbo',
      'out',
      '.env*.local',
      '.DS_Store',
      '*.pem',
      'apps/backend/dist',
      'apps/matrix-frontend/dist',
      'packages/*/dist',
      'packages/*/build',
      '.claude',
      '.git',
      'tests/**',
      '**/*.test.js',
      '**/*.test.ts',
      '**/*.spec.js',
      '**/*.spec.ts',
      'database/**',
      'scripts/**',
      'security/**',
      'test_*.js',
      'run-*.js',
      '*.config.js',
      'TEMPLATE_PROJECT/**',
      'utils/**',
      'tools/Strip/**',
      'ecosystem.config.cjs',
      '*.cjs',
      'desktop-app/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx,js,jsx}'],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        console: 'readonly',
        process: 'readonly',
        require: 'readonly',
        module: 'readonly',
        global: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        Buffer: 'readonly',
        navigator: 'readonly',
        document: 'readonly',
        window: 'readonly',
        setTimeout: 'readonly',
        WebSocket: 'readonly',
        CloseEvent: 'readonly',
        Event: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLElement: 'readonly',
        Document: 'readonly',
        MouseEvent: 'readonly',
        URL: 'readonly',
        alert: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        localStorage: 'readonly',
        getComputedStyle: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        chrome: 'readonly',
        fetch: 'readonly',
      },
    },
    plugins: {
      react: react,
      'react-hooks': reactHooks,
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-require-imports': 'warn',
      '@typescript-eslint/prefer-as-const': 'warn',
      'no-case-declarations': 'warn',
      'no-irregular-whitespace': 'warn',
      'no-empty': 'warn',
      'prefer-const': 'warn',
      'react-hooks/exhaustive-deps': 'warn',
      'react-hooks/rules-of-hooks': 'warn',
      'react/prop-types': 'off',
      'react/no-unescaped-entities': 'off',
      'react/no-unknown-property': 'warn',
      '@typescript-eslint/ban-ts-comment': 'warn',
    },
  },
];
