import React, { useState, useEffect, useCallback } from 'react';
import { useSemanticBrain } from '../src/hooks/useSemanticBrain';
import {
  Hammer, Brain, Sparkles, Code, Copy, Check,
  Play, ChevronDown, ChevronUp, Zap, History
} from 'lucide-react';

/**
 * The Architect - Intelligent Code Builder Widget
 *
 * Features:
 * - Semantic memory: Recalls past preferences and patterns
 * - Context-aware code generation
 * - Live preview capability
 * - Broadcasts insights for other widgets
 */

interface GeneratedComponent {
  id: string;
  prompt: string;
  code: string;
  timestamp: number;
  memories: string[];
}

const TheArchitectWidget: React.FC<{ widgetId?: string }> = ({ widgetId }) => {
  const [prompt, setPrompt] = useState('');
  const [generatedCode, setGeneratedCode] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [history, setHistory] = useState<GeneratedComponent[]>([]);
  const [showPreview, setShowPreview] = useState(false);

  // Semantic Brain - Widget Telepathy
  const {
    thoughts,
    isThinking: isRecalling,
    recall,
    broadcast,
    canDream,
    brainStatus
  } = useSemanticBrain('TheArchitect');

  // Debounced recall when user types
  useEffect(() => {
    if (prompt.length > 10) {
      const timer = setTimeout(() => {
        recall(prompt, { limit: 3, minScore: 0.5 });
      }, 800);
      return () => clearTimeout(timer);
    }
  }, [prompt, recall]);

  // Build enriched prompt with memories
  const buildEnrichedPrompt = useCallback(() => {
    if (thoughts.length === 0) return prompt;

    const memoryContext = thoughts
      .map(t => `- Previously noted: "${t.content}" (${t.agent}, relevance: ${(t.score * 100).toFixed(0)}%)`)
      .join('\n');

    return `
USER REQUEST: ${prompt}

CONTEXT FROM MEMORY (Use these to match user's style/preferences):
${memoryContext}

Generate clean, production-ready React TypeScript code. Apply any relevant patterns from memory.
    `.trim();
  }, [prompt, thoughts]);

  // Handle code generation
  const handleBuild = async () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);

    // Broadcast that we're starting work
    await broadcast('TOOL_SELECTION', `Starting code generation for: ${prompt.substring(0, 50)}...`);

    try {
      const enrichedPrompt = buildEnrichedPrompt();

      // Call backend API for code generation
      const response = await fetch('/api/mcp/route', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          tool: 'architect.generate',
          params: {
            prompt: enrichedPrompt,
            memories: thoughts.map(t => t.content),
            format: 'react-typescript'
          }
        })
      });

      let code = '';

      if (response.ok) {
        const data = await response.json();
        code = data.code || data.result?.code || generateFallbackCode(prompt);
      } else {
        // Fallback to local generation for demo
        code = generateFallbackCode(prompt);
      }

      setGeneratedCode(code);

      // Save to history
      const component: GeneratedComponent = {
        id: `comp-${Date.now()}`,
        prompt,
        code,
        timestamp: Date.now(),
        memories: thoughts.map(t => t.content)
      };
      setHistory(prev => [component, ...prev].slice(0, 10));

      // Broadcast insight about what was created
      await broadcast('INSIGHT', `Generated component: ${prompt.substring(0, 60)}`, {
        promptLength: prompt.length,
        memoriesUsed: thoughts.length,
        codeLength: code.length
      });

    } catch (error) {
      console.error('Generation failed:', error);
      setGeneratedCode('// Error generating code. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Fallback code generator (demo mode)
  const generateFallbackCode = (userPrompt: string): string => {
    const componentName = userPrompt
      .split(' ')
      .slice(0, 2)
      .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
      .join('') + 'Component';

    return `import React, { useState } from 'react';

interface ${componentName}Props {
  className?: string;
}

/**
 * ${componentName}
 * Generated by The Architect based on: "${userPrompt}"
 * ${thoughts.length > 0 ? `\n * Applied memories:\n${thoughts.map(t => ` *  - ${t.content}`).join('\n')}` : ''}
 */
export const ${componentName}: React.FC<${componentName}Props> = ({ className }) => {
  const [isActive, setIsActive] = useState(false);

  return (
    <div className={\`p-4 rounded-lg border border-slate-700 bg-slate-900 \${className}\`}>
      <h3 className="text-lg font-semibold text-white mb-2">
        ${componentName}
      </h3>
      <p className="text-slate-400 text-sm mb-4">
        {/* Component based on: ${userPrompt} */}
        Your content here...
      </p>
      <button
        onClick={() => setIsActive(!isActive)}
        className={\`px-4 py-2 rounded-lg transition-colors \${
          isActive
            ? 'bg-green-600 hover:bg-green-500'
            : 'bg-blue-600 hover:bg-blue-500'
        } text-white\`}
      >
        {isActive ? 'Active' : 'Activate'}
      </button>
    </div>
  );
};

export default ${componentName};
`;
  };

  // Copy to clipboard
  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-full flex flex-col bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white rounded-xl border border-amber-500/30 shadow-xl overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-white/10 bg-gradient-to-r from-amber-900/20 to-orange-900/20">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-amber-500/20 rounded-lg">
            <Hammer className="w-5 h-5 text-amber-400" />
          </div>
          <div>
            <h3 className="font-bold text-lg">The Architect</h3>
            <p className="text-xs text-slate-400">
              {canDream ? '🧠 Memory Active' : '💤 Memory Offline'}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {brainStatus && (
            <span className="text-xs text-slate-500">
              {brainStatus.metrics.totalThoughts} thoughts
            </span>
          )}
          <button
            onClick={() => setShowHistory(!showHistory)}
            className="p-2 hover:bg-white/10 rounded-lg transition-colors"
            title="Generation History"
          >
            <History className="w-4 h-4 text-slate-400" />
          </button>
        </div>
      </div>

      {/* Memory Indicator */}
      {thoughts.length > 0 && (
        <div className="mx-4 mt-3 p-3 bg-purple-900/20 border border-purple-500/30 rounded-lg">
          <div className="flex items-center gap-2 text-purple-300 text-xs font-medium mb-2">
            <Brain className="w-3 h-3" />
            <span>MEMORY ACTIVATED ({thoughts.length} relevant)</span>
            {isRecalling && <Sparkles className="w-3 h-3 animate-pulse" />}
          </div>
          <ul className="space-y-1">
            {thoughts.slice(0, 3).map((t, i) => (
              <li key={i} className="text-xs text-purple-200/70 truncate flex items-center gap-2">
                <span className="text-purple-400">•</span>
                <span className="flex-1 truncate">{t.content}</span>
                <span className="text-purple-400/50 text-[10px]">
                  {(t.score * 100).toFixed(0)}%
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Main Content */}
      <div className="flex-1 p-4 overflow-y-auto space-y-4">
        {/* Prompt Input */}
        <div>
          <label className="block text-sm font-medium text-slate-300 mb-2">
            What should I build?
          </label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Describe the component you want... e.g., 'A dark-themed dashboard card with a sparkline chart and status indicator'"
            rows={4}
            className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:outline-none focus:border-amber-500 resize-none"
          />
        </div>

        {/* Generate Button */}
        <button
          onClick={handleBuild}
          disabled={isGenerating || !prompt.trim()}
          className="w-full py-3 bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-500 hover:to-orange-500 disabled:from-slate-600 disabled:to-slate-600 rounded-lg font-semibold flex items-center justify-center gap-2 transition-all"
        >
          {isGenerating ? (
            <>
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Building...
            </>
          ) : (
            <>
              <Zap className="w-4 h-4" />
              Build Component
            </>
          )}
        </button>

        {/* Generated Code */}
        {generatedCode && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium text-slate-300">
                Generated Code
              </label>
              <div className="flex gap-2">
                <button
                  onClick={() => setShowPreview(!showPreview)}
                  className="px-3 py-1 text-xs bg-slate-700 hover:bg-slate-600 rounded-lg flex items-center gap-1"
                >
                  <Play className="w-3 h-3" />
                  Preview
                </button>
                <button
                  onClick={handleCopy}
                  className="px-3 py-1 text-xs bg-slate-700 hover:bg-slate-600 rounded-lg flex items-center gap-1"
                >
                  {copied ? (
                    <>
                      <Check className="w-3 h-3 text-green-400" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="w-3 h-3" />
                      Copy
                    </>
                  )}
                </button>
              </div>
            </div>
            <div className="relative">
              <pre className="bg-slate-950 border border-slate-700 rounded-lg p-4 overflow-x-auto text-sm text-slate-300 max-h-80">
                <code>{generatedCode}</code>
              </pre>
              <div className="absolute top-2 right-2">
                <Code className="w-4 h-4 text-slate-600" />
              </div>
            </div>
          </div>
        )}

        {/* History Panel */}
        {showHistory && history.length > 0 && (
          <div className="border-t border-slate-700 pt-4">
            <h4 className="text-sm font-medium text-slate-300 mb-3 flex items-center gap-2">
              <History className="w-4 h-4" />
              Recent Builds
            </h4>
            <div className="space-y-2 max-h-40 overflow-y-auto">
              {history.map((item) => (
                <button
                  key={item.id}
                  onClick={() => {
                    setPrompt(item.prompt);
                    setGeneratedCode(item.code);
                  }}
                  className="w-full text-left p-3 bg-slate-800/50 hover:bg-slate-700/50 rounded-lg transition-colors"
                >
                  <p className="text-sm text-white truncate">{item.prompt}</p>
                  <div className="flex items-center gap-2 mt-1 text-xs text-slate-500">
                    <span>{new Date(item.timestamp).toLocaleTimeString()}</span>
                    {item.memories.length > 0 && (
                      <span className="text-purple-400">
                        +{item.memories.length} memories
                      </span>
                    )}
                  </div>
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="p-3 border-t border-white/10 bg-slate-900/50 text-center">
        <p className="text-[10px] text-slate-500">
          The Architect learns from your preferences via the Semantic Bus
        </p>
      </div>
    </div>
  );
};

export default TheArchitectWidget;
