import React, { useState, useEffect, useCallback } from 'react';
import { useSemanticBrain } from '../src/hooks/useSemanticBrain';
import { MatrixWidgetWrapper } from '../src/components/MatrixWidgetWrapper';
import {
  Hammer, Brain, Sparkles, Code, Copy, Check,
  Play, History, Zap
} from 'lucide-react';

/**
 * The Architect - Intelligent Code Builder Widget
 */

interface GeneratedComponent {
  id: string;
  prompt: string;
  code: string;
  timestamp: number;
  memories: string[];
}

const TheArchitectWidget: React.FC<{ widgetId?: string }> = ({ widgetId }) => {
  const [prompt, setPrompt] = useState('');
  const [generatedCode, setGeneratedCode] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [history, setHistory] = useState<GeneratedComponent[]>([]);
  const [showPreview, setShowPreview] = useState(false);

  // Semantic Brain - Widget Telepathy
  const {
    thoughts,
    isThinking: isRecalling,
    recall,
    broadcast,
    canDream,
    brainStatus
  } = useSemanticBrain('TheArchitect');

  // Debounced recall when user types
  useEffect(() => {
    if (prompt.length > 10) {
      const timer = setTimeout(() => {
        recall(prompt, { limit: 3, minScore: 0.5 });
      }, 800);
      return () => clearTimeout(timer);
    }
  }, [prompt, recall]);

  // Build enriched prompt with memories
  const buildEnrichedPrompt = useCallback(() => {
    if (thoughts.length === 0) return prompt;

    const memoryContext = thoughts
      .map(t => `- Previously noted: "${t.content}" (${t.agent}, relevance: ${(t.score * 100).toFixed(0)}%)`)
      .join('\n');

    return `
USER REQUEST: ${prompt}

CONTEXT FROM MEMORY (Use these to match user's style/preferences):
${memoryContext}

Generate clean, production-ready React TypeScript code. Apply any relevant patterns from memory.
    `.trim();
  }, [prompt, thoughts]);

  // Handle code generation
  const handleBuild = async () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);

    // Broadcast that we're starting work
    await broadcast('TOOL_SELECTION', `Starting code generation for: ${prompt.substring(0, 50)}...`);

    try {
      const enrichedPrompt = buildEnrichedPrompt();

      // Call backend API for code generation
      const response = await fetch('/api/mcp/route', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          tool: 'architect.generate',
          params: {
            prompt: enrichedPrompt,
            memories: thoughts.map(t => t.content),
            format: 'react-typescript'
          }
        })
      });

      let code = '';

      if (response.ok) {
        const data = await response.json();
        code = data.code || data.result?.code || generateFallbackCode(prompt);
      } else {
        // Fallback to local generation for demo
        code = generateFallbackCode(prompt);
      }

      setGeneratedCode(code);

      // Save to history
      const component: GeneratedComponent = {
        id: `comp-${Date.now()}`,
        prompt,
        code,
        timestamp: Date.now(),
        memories: thoughts.map(t => t.content)
      };
      setHistory(prev => [component, ...prev].slice(0, 10));

      // Broadcast insight about what was created
      await broadcast('INSIGHT', `Generated component: ${prompt.substring(0, 60)}`, {
        promptLength: prompt.length,
        memoriesUsed: thoughts.length,
        codeLength: code.length
      });

    } catch (error) {
      console.error('Generation failed:', error);
      setGeneratedCode('// Error generating code. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Fallback code generator (demo mode)
  const generateFallbackCode = (userPrompt: string): string => {
    const componentName = userPrompt
      .split(' ')
      .slice(0, 2)
      .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
      .join('') + 'Component';

    return `import React, { useState } from 'react';

interface ${componentName}Props {
  className?: string;
}

/**
 * ${componentName}
 * Generated by The Architect based on: "${userPrompt}"
 * ${thoughts.length > 0 ? `\n * Applied memories:\n${thoughts.map(t => ` *  - ${t.content}`).join('\n')}` : ''}
 */
export const ${componentName}: React.FC<${componentName}Props> = ({ className }) => {
  const [isActive, setIsActive] = useState(false);

  return (
    <div className={\`p-4 rounded-lg border border-slate-700 bg-slate-900 \${className}\`}>
      <h3 className="text-lg font-semibold text-white mb-2">
        ${componentName}
      </h3>
      <p className="text-slate-400 text-sm mb-4">
        {/* Component based on: ${userPrompt} */}
        Your content here...
      </p>
      <button
        onClick={() => setIsActive(!isActive)}
        className={\`px-4 py-2 rounded-lg transition-colors \${
          isActive
            ? 'bg-green-600 hover:bg-green-500'
            : 'bg-blue-600 hover:bg-blue-500'
        } text-white\`}
      >
        {isActive ? 'Active' : 'Activate'}
      </button>
    </div>
  );
};

export default ${componentName};
`;
  };

  // Copy to clipboard
  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <MatrixWidgetWrapper 
        title="The Architect" 
        controls={
            <button
                onClick={() => setShowHistory(!showHistory)}
                className={`p-1 rounded hover:text-[#00B5CB] transition-colors ${showHistory ? 'text-[#00B5CB]' : 'text-gray-400'}`}
                title="History"
            >
                <History size={14} />
            </button>
        }
    >
      <div className="flex flex-col gap-4 h-full">
         {/* Memory Indicator */}
        {thoughts.length > 0 && (
            <div className="p-2 bg-purple-500/10 border border-purple-500/20 rounded-lg flex items-start gap-2 animate-fade-in">
                <Brain className="w-3 h-3 text-purple-400 mt-0.5 shrink-0" />
                <div className="flex-1 overflow-hidden">
                    <div className="flex items-center gap-2 text-[10px] font-bold text-purple-300 uppercase tracking-wider mb-1">
                        Active Memory Context ({thoughts.length})
                        {isRecalling && <Sparkles className="w-2 h-2 animate-pulse" />}
                    </div>
                    <div className="flex flex-wrap gap-1">
                         {thoughts.slice(0, 3).map((t, i) => (
                            <span key={i} className="text-[9px] px-1.5 py-0.5 bg-purple-500/20 rounded text-purple-200 truncate max-w-[150px]" title={t.content}>
                                {t.content}
                            </span>
                        ))}
                    </div>
                </div>
            </div>
        )}

        {/* Prompt Input */}
        <div className="relative">
            <div className="absolute top-3 left-3 text-amber-500/50">
                 <Hammer size={16} />
            </div>
             <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Describe the component you want to build..."
                className="w-full bg-black/20 border border-white/10 rounded-xl pl-10 pr-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-amber-500/50 focus:ring-1 focus:ring-amber-500/20 resize-none min-h-[80px]"
            />
            <button
                onClick={handleBuild}
                disabled={isGenerating || !prompt.trim()}
                className="absolute bottom-2 right-2 p-1.5 bg-amber-600 hover:bg-amber-500 text-white rounded-lg disabled:opacity-50 disabled:cursor-not-allowed transition-colors shadow-lg shadow-amber-900/20"
            >
                {isGenerating ? <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <Zap size={16} />}
            </button>
        </div>

        {/* Output Area */}
        <div className="flex-1 min-h-0 flex flex-col relative">
            {generatedCode ? (
                 <div className="flex-1 bg-[#0F1117] border border-white/10 rounded-xl overflow-hidden flex flex-col">
                     <div className="h-8 flex items-center justify-between px-3 border-b border-white/5 bg-white/5">
                         <span className="text-[10px] font-mono text-gray-400 flex items-center gap-1">
                             <Code size={10} /> REACT COMPONENT
                         </span>
                         <div className="flex items-center gap-2">
                            <button
                                onClick={() => setShowPreview(!showPreview)}
                                className={`text-[10px] px-2 py-0.5 rounded transition-colors ${showPreview ? 'bg-amber-500/20 text-amber-400' : 'text-gray-400 hover:text-white'}`}
                            >
                                <Play size={10} className="inline mr-1" /> Preview
                            </button>
                            <button
                                onClick={handleCopy}
                                className="text-[10px] px-2 py-0.5 rounded text-gray-400 hover:text-white hover:bg-white/10 transition-colors"
                            >
                                {copied ? <Check size={10} className="inline mr-1 text-green-400" /> : <Copy size={10} className="inline mr-1" />}
                                {copied ? 'Copied' : 'Copy'}
                            </button>
                         </div>
                     </div>
                     <div className="flex-1 overflow-auto p-3 custom-scrollbar">
                         <pre className="text-xs font-mono text-gray-300 leading-relaxed">
                             {generatedCode}
                         </pre>
                     </div>
                 </div>
            ) : (
                <div className="flex-1 flex flex-col items-center justify-center border border-dashed border-white/10 rounded-xl text-gray-500/40 gap-2">
                     <Hammer size={32} strokeWidth={1} />
                     <p className="text-xs">Awaiting architecture specifications</p>
                </div>
            )}
        </div>

         {/* History Overlay */}
         {showHistory && history.length > 0 && (
            <div className="absolute inset-x-4 bottom-4 top-20 bg-[#0B1015]/95 backdrop-blur-xl border border-white/10 rounded-xl p-3 z-20 flex flex-col animate-fade-in">
                <div className="flex items-center justify-between mb-2 pb-2 border-b border-white/5">
                     <h4 className="text-xs font-bold text-gray-300 uppercase">Build History</h4>
                     <button onClick={() => setShowHistory(false)} className="text-gray-500 hover:text-white">Close</button>
                </div>
                <div className="flex-1 overflow-y-auto space-y-2 custom-scrollbar">
                    {history.map((item) => (
                        <button
                            key={item.id}
                            onClick={() => {
                                setPrompt(item.prompt);
                                setGeneratedCode(item.code);
                                setShowHistory(false);
                            }}
                            className="w-full text-left p-2 rounded-lg hover:bg-white/5 transition-colors group"
                        >
                            <p className="text-xs text-gray-300 truncate group-hover:text-amber-400 transition-colors">{item.prompt}</p>
                            <span className="text-[10px] text-gray-600">{new Date(item.timestamp).toLocaleTimeString()}</span>
                        </button>
                    ))}
                </div>
            </div>
         )}

      </div>
    </MatrixWidgetWrapper>
  );
};

export default TheArchitectWidget;
