import { lazy } from 'react';

// Hardcoded registry to bypass import.meta.glob issues
// All widgets explicitly linked for guaranteed loading
export const staticWidgetRegistry: Record<string, any> = {
  // Core Widgets
  'ActivityStreamWidget': lazy(() => import('../widgets/ActivityStreamWidget')),
  'AgentBuilderWidget': lazy(() => import('../widgets/AgentBuilderWidget')),
  'AgentChatWidget': lazy(() => import('../widgets/AgentChatWidget')),
  'AgentStatusDashboardWidget': lazy(() => import('../widgets/AgentStatusDashboardWidget')),
  'AiPalWidget': lazy(() => import('../widgets/AiPalWidget')),
  'AudioTranscriberWidget': lazy(() => import('../widgets/AudioTranscriberWidget')),
  'CmaDecisionWidget': lazy(() => import('../widgets/CmaDecisionWidget')),
  'CodeAnalysisWidget': lazy(() => import('../widgets/CodeAnalysisWidget')),
  'CybersecurityOverwatchWidget': lazy(() => import('../widgets/CybersecurityOverwatchWidget')),
  'DarkWebMonitorWidget': lazy(() => import('../widgets/DarkWebMonitorWidget')),
  'EvolutionAgentWidget': lazy(() => import('../widgets/EvolutionAgentWidget')),
  'FeedIngestionWidget': lazy(() => import('../widgets/FeedIngestionWidget')),
  'ImageAnalyzerWidget': lazy(() => import('../widgets/ImageAnalyzerWidget')),
  'IntelligentNotesWidget': lazy(() => import('../widgets/IntelligentNotesWidget')),
  'KanbanWidget': lazy(() => import('../widgets/KanbanWidget')),
  'LiveConversationWidget': lazy(() => import('../widgets/LiveConversationWidget')),
  'LocalScanWidget': lazy(() => import('../widgets/LocalScanWidget')),
  'MCPConnectorWidget': lazy(() => import('../widgets/MCPConnectorWidget')),
  'MCPEmailRAGWidget': lazy(() => import('../widgets/MCPEmailRAGWidget')),
  'McpRouterWidget': lazy(() => import('../widgets/McpRouterWidget')),
  'NetworkSpyWidget': lazy(() => import('../widgets/NetworkSpyWidget')),
  'NexusTerminalWidget': lazy(() => import('../widgets/NexusTerminalWidget')),
  'PerformanceMonitorWidget': lazy(() => import('../widgets/PerformanceMonitorWidget')),
  'PersonaCoordinatorWidget': lazy(() => import('../widgets/PersonaCoordinatorWidget')),
  'PersonalAgentWidget': lazy(() => import('../widgets/PersonalAgentWidget')),
  'Phase1CFastTrackKanbanWidget': lazy(() => import('../widgets/Phase1CFastTrackKanbanWidget')),
  'ProcurementIntelligenceWidget': lazy(() => import('../widgets/ProcurementIntelligenceWidget')),
  'PromptLibraryWidget': lazy(() => import('../widgets/PromptLibraryWidget')),
  'SearchInterfaceWidget': lazy(() => import('../widgets/SearchInterfaceWidget')),
  'SragGovernanceWidget': lazy(() => import('../widgets/SragGovernanceWidget')),
  'StatusWidget': lazy(() => import('../widgets/StatusWidget')),
  'SystemMonitorWidget': lazy(() => import('../widgets/SystemMonitorWidget')),
  'SystemSettingsWidget': lazy(() => import('../widgets/SystemSettingsWidget')),
  'VideoAnalyzerWidget': lazy(() => import('../widgets/VideoAnalyzerWidget')),
  'WidgetImporterWidget': lazy(() => import('../widgets/WidgetImporterWidget')),
};

// Widget metadata for display
export const widgetMetadata: Record<string, { name: string; description: string; category: string; defaultLayout: { w: number; h: number } }> = {
  'ActivityStreamWidget': { name: 'Activity Stream', description: 'Real-time activity feed', category: 'monitoring', defaultLayout: { w: 6, h: 2 } },
  'AgentBuilderWidget': { name: 'Agent Builder', description: 'Build custom AI agents', category: 'agents', defaultLayout: { w: 6, h: 3 } },
  'AgentChatWidget': { name: 'Agent Chat', description: 'Chat with AI agents', category: 'communication', defaultLayout: { w: 4, h: 3 } },
  'AgentStatusDashboardWidget': { name: 'Agent Status', description: 'Agent status overview', category: 'agents', defaultLayout: { w: 8, h: 2 } },
  'AiPalWidget': { name: 'AI Pal', description: 'Personal AI assistant', category: 'ai', defaultLayout: { w: 4, h: 3 } },
  'AudioTranscriberWidget': { name: 'Audio Transcriber', description: 'Transcribe audio to text', category: 'media', defaultLayout: { w: 6, h: 2 } },
  'CmaDecisionWidget': { name: 'CMA Decision', description: 'Decision analysis', category: 'analytics', defaultLayout: { w: 6, h: 2 } },
  'CodeAnalysisWidget': { name: 'Code Analysis', description: 'Analyze code quality', category: 'development', defaultLayout: { w: 8, h: 3 } },
  'CybersecurityOverwatchWidget': { name: 'Cybersecurity Overwatch', description: 'Security monitoring', category: 'security', defaultLayout: { w: 8, h: 3 } },
  'DarkWebMonitorWidget': { name: 'Dark Web Monitor', description: 'Monitor dark web threats', category: 'security', defaultLayout: { w: 6, h: 3 } },
  'EvolutionAgentWidget': { name: 'Evolution Agent', description: 'Self-evolving AI', category: 'agents', defaultLayout: { w: 6, h: 2 } },
  'FeedIngestionWidget': { name: 'Feed Ingestion', description: 'Process data feeds', category: 'data', defaultLayout: { w: 6, h: 2 } },
  'ImageAnalyzerWidget': { name: 'Image Analyzer', description: 'AI image analysis', category: 'media', defaultLayout: { w: 6, h: 3 } },
  'IntelligentNotesWidget': { name: 'Intelligent Notes', description: 'Smart note-taking', category: 'productivity', defaultLayout: { w: 4, h: 3 } },
  'KanbanWidget': { name: 'Kanban Board', description: 'Task management', category: 'productivity', defaultLayout: { w: 12, h: 3 } },
  'LiveConversationWidget': { name: 'Live Conversation', description: 'Real-time chat', category: 'communication', defaultLayout: { w: 6, h: 3 } },
  'LocalScanWidget': { name: 'Local Scan', description: 'Scan local system', category: 'security', defaultLayout: { w: 6, h: 2 } },
  'MCPConnectorWidget': { name: 'MCP Connector', description: 'Connect to MCP', category: 'integration', defaultLayout: { w: 4, h: 2 } },
  'MCPEmailRAGWidget': { name: 'MCP Email RAG', description: 'Email RAG processing', category: 'integration', defaultLayout: { w: 6, h: 3 } },
  'McpRouterWidget': { name: 'MCP Router', description: 'Route MCP messages', category: 'integration', defaultLayout: { w: 6, h: 2 } },
  'NetworkSpyWidget': { name: 'Network Spy', description: 'Monitor network', category: 'security', defaultLayout: { w: 6, h: 2 } },
  'NexusTerminalWidget': { name: 'Nexus Terminal', description: 'AI-powered terminal', category: 'development', defaultLayout: { w: 12, h: 3 } },
  'PerformanceMonitorWidget': { name: 'Performance Monitor', description: 'System metrics', category: 'monitoring', defaultLayout: { w: 6, h: 2 } },
  'PersonaCoordinatorWidget': { name: 'Persona Coordinator', description: 'Manage AI personas', category: 'agents', defaultLayout: { w: 6, h: 2 } },
  'PersonalAgentWidget': { name: 'Personal Agent', description: 'Your personal AI', category: 'agents', defaultLayout: { w: 4, h: 2 } },
  'Phase1CFastTrackKanbanWidget': { name: 'Fast Track Kanban', description: 'Project management', category: 'productivity', defaultLayout: { w: 12, h: 3 } },
  'ProcurementIntelligenceWidget': { name: 'Procurement Intelligence', description: 'Procurement insights', category: 'analytics', defaultLayout: { w: 6, h: 2 } },
  'PromptLibraryWidget': { name: 'Prompt Library', description: 'Manage AI prompts', category: 'ai', defaultLayout: { w: 6, h: 3 } },
  'SearchInterfaceWidget': { name: 'Search Interface', description: 'Advanced search', category: 'productivity', defaultLayout: { w: 8, h: 2 } },
  'SragGovernanceWidget': { name: 'SRAG Governance', description: 'Compliance monitoring', category: 'compliance', defaultLayout: { w: 6, h: 2 } },
  'StatusWidget': { name: 'Status', description: 'System status', category: 'monitoring', defaultLayout: { w: 4, h: 1 } },
  'SystemMonitorWidget': { name: 'System Monitor', description: 'System monitoring', category: 'monitoring', defaultLayout: { w: 6, h: 2 } },
  'SystemSettingsWidget': { name: 'System Settings', description: 'Configure settings', category: 'settings', defaultLayout: { w: 6, h: 3 } },
  'VideoAnalyzerWidget': { name: 'Video Analyzer', description: 'AI video analysis', category: 'media', defaultLayout: { w: 8, h: 3 } },
  'WidgetImporterWidget': { name: 'Widget Importer', description: 'Import widgets', category: 'system', defaultLayout: { w: 6, h: 2 } },
};
